language: node_js

node_js:
    - "stable"
    - "7"
    - "6"
    - "5"
    - "4"

os:
    - linux

branches:
    only:
        - master

env:
    - NODE_ENV=TEST

install:
    - npm install

script:
    - npm test
    - npm run coverage
