language: node_js

node_js:
    - "node"
    - "4"

os:
    - linux
    - osx

env:
    - NODE_ENV=TEST

before_install:
    - npm run print-banner

install:
    - npm install

script:
    - npm run print-banner
    - npm test

notifications:
    email: "smallela.projworks@gmail.com"

