language: node_js

node_js:
    - "node"
    - "4"

os:
    - linux

env:
    - NODE_ENV=TEST

install:
    - npm install

script:
    - ls -ltr ./bin
    - npm run print-banner --verbose
    - npm test

notifications:
    email: "smallela.projworks@gmail.com"

