environment:
    matrix:
        - nodejs_version: "4"
        - nodejs_version: "5"
        - nodejs_version: "6"
        - nodejs_version: "7"
        - nodejs_version: "8"
        - nodejs_version: "9"
cache:
    - node_modules
install:
    - npm install
build:
    - npm run build
test_script:
    - node --version
    - npm --version
version: "{build}"
