environment:
  matrix:
    - nodejs_version: "16"
    - nodejs_version: "18"
    - nodejs_version: "20"
cache:
  - node_modules
install:
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm run build
version: "{build}"
